// ══════════════════════════════════════════════════════════════
//  authStyles.ts — 로그인·회원가입 공통 색상 토큰 & 스타일
// ══════════════════════════════════════════════════════════════
import { StyleSheet } from "react-native";

export const C = {
  accent: "#7c6fff",
  text: "#1a1a2e",
  sub: "#666",
  border: "#e8e8f0",
  bg: "#ffffff",
  red: "#ef4444",
};

/** 로그인·회원가입 모달 공통 스타일 */
export const mo = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15,15,30,0.55)",
  },
  card: {
    width: "100%",
    maxWidth: 460,
    backgroundColor: C.bg,
    borderRadius: 22,
    paddingTop: 4,
    paddingBottom: 28,
    paddingHorizontal: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 28 },
    shadowOpacity: 0.18,
    shadowRadius: 48,
    elevation: 20,
  },
  topBar: {
    height: 4,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    marginHorizontal: -24,
    marginBottom: 20,
    backgroundColor: C.accent,
  },
  xBtn: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f3f8",
  },
  xTxt: { fontSize: 14, color: "#888", fontWeight: "700" as const },
  hd: { alignItems: "center", marginBottom: 18 },
  logoBox: {
    width: 100,
    height: 100,
    borderRadius: 13,
    // backgroundColor: C.accent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: C.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 6,
  },
  logoTxt: { color: "#fff", fontWeight: "900" as const, fontSize: 17 },
  title: {
    fontSize: 22,
    fontWeight: "900" as const,
    color: C.text,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  sub: { fontSize: 13, color: C.sub, lineHeight: 20 },
  lbl: { fontSize: 12, fontWeight: "700" as const, color: "#555" },
  inp: {
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 10,
    padding: 11,
    fontSize: 14,
    color: C.text,
    backgroundColor: C.bg,
  },
  inpFoc: { borderColor: C.accent },
  inpErr: { borderColor: C.red },
  errBox: {
    backgroundColor: "rgba(239,68,68,0.07)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.2)",
    borderRadius: 8,
    padding: 10,
  },
  errTxt: { fontSize: 12, fontWeight: "600" as const, color: C.red },
  errField: { fontSize: 11, fontWeight: "600" as const, color: C.red },
  btn: {
    backgroundColor: C.accent,
    borderRadius: 11,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: C.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.32,
    shadowRadius: 14,
    elevation: 6,
  },
  btnTxt: { fontSize: 15, fontWeight: "700" as const, color: "#fff" },
  backBtn: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 11,
    alignItems: "center",
  },
  backTxt: { fontSize: 14, fontWeight: "700" as const, color: C.sub },
  sw: { flexDirection: "row", justifyContent: "center", marginTop: 14 },
  swTxt: { fontSize: 13, color: C.sub },
  swLink: {
    fontSize: 13,
    fontWeight: "700" as const,
    color: C.accent,
    textDecorationLine: "underline" as const,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1.5,
  },
  badgeTxt: { fontSize: 14, fontWeight: "700" as const },
});
